# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -O3 -DNDEBUG -I/home/matthias/head_pose_estimation/demo/. -I/home/matthias/head_pose_estimation/demo/.. -I/home/matthias/OpenNI/Include -I/usr/local/include -I/home/matthias/liblo-0.26  

CXX_DEFINES = 

